# Example config for `python processor.py --config <this file>`
city: Berlin
target_epsg: EPSG:32633

inputs:
  sentinel2: /mnt/d/LXM/Phd/Research/HEATWISE/CHIME/Sentinel-2/Berlin_S2_2024-10-24.tif
  hsi: /mnt/d/LXM/Phd/Research/HEATWISE/CHIME/output/heatwise-hsi-lst-prep-run/03_hsi_final/hsi_bs/Berlin_hsi_bs.tif
  pca: /mnt/d/LXM/Phd/Research/HEATWISE/CHIME/output/heatwise-hsi-lst-prep-run/03_hsi_final/hsi_pca/Berlin_hsi_pca.tif  # only read if toggles.use_pca
  lst: /mnt/d/LXM/Phd/Research/HEATWISE/CHIME/output/heatwise-hsi-lst-prep-run/04_lst_final/Berlin_lst_final.tif  # only read if toggles.use_lst

labels:
  kml: /mnt/d/LXM/Phd/Research/HEATWISE/CHIME/Sample/1/Berlin.kml     # used only if `shp` below doesn't already exist
  shp: /mnt/d/LXM/Phd/Research/HEATWISE/CHIME/Sample/1/Berlin.shp
  class_column: Name
  min_area: 50000
  remap_dict: {1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11, 12: 12, 13: 13, 14: 14, 15: 15, 16: 16, 17: 17}
  class_order: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
  overlap_threshold: 0.6
  overlap_threshold_by_class:
    17: 0.35

sampling:
  grid_patch_size: 8
  resolution: 10
  patch_size: 32

split:
  block_m: 500.0
  super_block_m: 2500.0
  split_ratio: [0.6, 0.2, 0.2]
  min_sb_for_geo: 3
  seed_search: 300
  random_seed: 42

toggles:
  use_lst: true
  use_pca: true

output:
  h5_path: /mnt/d/LXM/Phd/Research/HEATWISE/CHIME/output/Patch/Berlin_block500.h5
